### ISSUE TITLE
Directory Issues / "Learn" not working

### ISSUE THREAD

**Issue by SCDesigns** [learn-co-curriculum/ruby-object-attributes-lab#7]
This issue is in regard to my ability to completing this lesson in the Learn IDE. Firstly, upon opening I am prompted that this is not the current lesson I am on; which is simply not true. 

// ♥ learn open ruby-object-attributes-lab-v-000  
Looking for lesson...  
WARNING: You are attempting to open a lesson that is beyond your current lesson.  
Are you sure you want to continue? [Yn]: y  
Bundling...  
Opening lesson...  
Done.

Secondly, despite entering and saving my input the "learn" command doesn't recognize my input in regards to the conditions of the test.

**Comment by AnnJohn** [comment]
hi @SCDesigns could you please use Ask a Question in Learn and someone will help you troubleshoot this problem. Thanks!
