### ISSUE TITLE
IDE will not load my current lesson lab files

### ISSUE THREAD

**Issue by aliciayu** [learn-co-curriculum/ruby-object-attributes-lab#9]
When I try to open the lab in Learn IDE it asks me if I want to open a lesson that is beyond my current lesson. I answer "Y". It is the current lesson I am on. It does the same with lessons I have previously completed. It however does not open the lesson. It then proceeds to get stuck on Learn IDE  trying to loading the files for that lesson, including the README. If I try to save any changes to the files. It will not save. It remains trying to load the files, but does not accomplish loading the files. I have not had this issue in the past.

I get the following messages from Learn IDE:
Learn IDE: loading README.md... Please leave this file blank and the contents will appear automatically (as you long as you have not altered the file)

Learn IDE: loading dog.rb... Please leave this file blank and the contents will appear automatically (as you long as you have not altered the file)

I have logged off and exited out of Learn IDE and shut my compute off . I had the same issue. So then I repeated the same process except I restarted my computer. Again I am having the same issue. I have had this issue since Friday (June 16).

**Comment by JeffKatzy** [comment]
I am moving this to an ide issue.
